# Conditional probabilities

Generate feature 2 based on feature 1.

## Code setup

In [1]:
import numpy as np
import pandas as pd

## Create data

Or load in a .csv if you have it!

Here, create some data so that most of the values are small and the values along the diagonal are much bigger.

In [2]:
d = np.full((5, 5), 0.1)

for i in range(5):
    d[i, i] = 1.6

d = d / np.sum(d)

Put that grid into a dataframe:

In [3]:
df_c = pd.DataFrame(
    d,
    columns=['a', 'b', 'c', 'd', 'e'],
    index=['v', 'w', 'x', 'y', 'z']
)

In [4]:
df_c

      a     b     c     d     e
v  0.16  0.01  0.01  0.01  0.01
w  0.01  0.16  0.01  0.01  0.01
x  0.01  0.01  0.16  0.01  0.01
y  0.01  0.01  0.01  0.16  0.01
z  0.01  0.01  0.01  0.01  0.16

## Generate data

Generate this many values:

In [5]:
num_rows = 100

Generate feature 1 based on the total probabilities of each value.

In [6]:
# Generate feature 1:
vals_f1 = df_c.columns
probs_f1 = df_c.sum(axis='rows')  # for each column, sum all its values
f1 = np.random.choice(vals_f1, size=num_rows, p=probs_f1)

Now for each value of feature 1 in turn, generate some values for feature 2. This lets feature 2 use a different set of probabilities each time.

In [7]:
# Create an empty array for feature 2:
f2 = np.full(len(f1), 'q')  # 'q' is our definitely-wrong value
vals_f2 = df_c.index

# For each option for feature 1, pick out the probabilities for feature 2:
for v in vals_f1:
    # Which indices of f1 have this value?
    inds_v = np.where(f1 == v)
    # How many of our generated f1 have this value?
    num_v = len(inds_v[0])
    # Probabilities for this value of f1:
    probs_v = df_c[v]
    # Normalise (make them sum to 1):
    probs_v = probs_v / probs_v.sum()
    # Generate new values for feature 2 for this value of feature 1:
    f2_v = np.random.choice(vals_f2, size=num_v, p=probs_v)
    # Place these into the main f2 array:
    f2[inds_v] = f2_v

    # Print this to show what's happening:
    # print(v, num_v, probs_v, f2_v)

Gather the resulting data:

In [8]:
pd.DataFrame([f1, f2]).T

    0  1
0   d  y
1   b  w
2   a  v
3   c  x
4   c  z
.. .. ..
95  e  z
96  c  x
97  a  v
98  b  v
99  a  y

[100 rows x 2 columns]