# Example of writing out the linear regression formula

Use the effects lookup to make a string with the formula in it.

## Code setup

In [2]:
import pandas as pd
import os

## Load in effects dictionary

In [3]:
df_effects = pd.read_csv(os.path.join('.', 'effects_linreg_allpatients_mrsleq2.csv'), index_col=0)

In [6]:
with pd.option_context('display.max_rows', 200): display(df_effects)

,precise_onset_known,afib_anticoagulant,prior_util,arrival_to_scan_time,thrombolysis,discharge_util,discharge_mrsleq2
onset_during_sleep,-0.65821,NaN,NaN,NaN,-0.11876,NaN,NaN
precise_onset_known,NaN,NaN,NaN,NaN,0.14176,NaN,NaN
atrial_fibrillation,NaN,0.63438,NaN,NaN,NaN,-0.02679,-0.02420
afib_anticoagulant,NaN,NaN,NaN,NaN,NaN,NaN,NaN
prior_util,NaN,NaN,NaN,NaN,0.36069,0.55124,0.77955
age_80plus,NaN,NaN,-0.11836,NaN,-0.04444,-0.10816,-0.14663
stroke_severity_mild,NaN,NaN,NaN,NaN,-0.06370,0.12423,0.18851
stroke_severity_moderate,NaN,NaN,NaN,NaN,0.18796,-0.11943,-0.14345
stroke_severity_severe,NaN,NaN,NaN,NaN,-0.05008,-0.41916,-0.29924
arrival_to_scan_time,NaN,NaN,NaN,NaN,-0.00184,NaN,NaN
2,NaN,NaN,NaN,14.49148,-0.01882,-0.02069,0.01357
3,NaN,NaN,NaN,-2.59155,-0.08621,-0.02396,-0.02492
5,NaN,NaN,NaN,5.02441,0.00785,0.05376,0.09234
6,NaN,NaN,NaN,2.68727,-0.01527,-0.02512,-0.18424
7,NaN,NaN,NaN,1.75067,0.11478,0.02417,0.02269
8,NaN,NaN,NaN,-5.98839,-0.03080,-0.00289,0.02226
9,NaN,NaN,NaN,-6.61990,0.02531,-0.04794,-0.09656
11,NaN,NaN,NaN,-7.22668,-0.01732,0.01919,0.06891
12,NaN,NaN,NaN,-0.28981,-0.03958,-0.02764,-0.03845
13,NaN,NaN,NaN,-11.92315,0.13107,0.00432,0.01471
14,NaN,NaN,NaN,-10.13793,0.00124,-0.01573,-0.03735
18,NaN,NaN,NaN,-19.23607,0.10557,-0.03516,-0.02045
20,NaN,NaN,NaN,-3.59080,-0.01621,-0.03574,-0.06754
21,NaN,NaN,NaN,0.41599,-0.03492,-0.02863,-0.07097
24,NaN,NaN,NaN,-3.20039,-0.01666,-0.02069,-0.02099
25,NaN,NaN,NaN,4.42180,-0.01175,0.00336,0.04791
28,NaN,NaN,NaN,11.74206,0.07225,0.01207,0.06327
29,NaN,NaN,NaN,-8.87706,-0.10890,-0.02710,-0.04577
31,NaN,NaN,NaN,1.51537,0.09349,0.04575,0.13651
32,NaN,NaN,NaN,2.29567,-0.04560,0.03095,0.07169
33,NaN,NaN,NaN,8.43163,-0.01146,0.03335,0.07808
34,NaN,NaN,NaN,-9.01314,0.00666,0.00183,-0.03219
36,NaN,NaN,NaN,11.70692,-0.02694,-0.04935,-0.09299
38,NaN,NaN,NaN,0.89889,-0.05202,-0.02442,-0.04848
39,NaN,NaN,NaN,-8.73276,-0.11137,-0.03222,-0.02576
40,NaN,NaN,NaN,0.96216,-0.01966,-0.02753,-0.08117
42,NaN,NaN,NaN,7.38487,-0.09891,0.02367,-0.02130
43,NaN,NaN,NaN,0.25931,-0.03479,-0.06169,-0.12425
45,NaN,NaN,NaN,-7.36292,-0.01351,-0.01228,0.02328
47,NaN,NaN,NaN,-14.72665,-0.00345,-0.04340,-0.05735
48,NaN,NaN,NaN,0.55161,0.01980,-0.02690,-0.03080
49,NaN,NaN,NaN,10.08602,-0.02367,0.07387,0.17085
51,NaN,NaN,NaN,-14.92004,-0.02806,0.00063,0.06909
55,NaN,NaN,NaN,-2.85577,0.01118,0.08430,0.12274
56,NaN,NaN,NaN,-13.06753,-0.09347,0.01694,0.02346
58,NaN,NaN,NaN,-8.57540,-0.17357,0.02425,0.08503
60,NaN,NaN,NaN,-4.48236,-0.04055,-0.01153,-0.09197
61,NaN,NaN,NaN,3.46784,-0.00266,-0.02119,-0.07610
62,NaN,NaN,NaN,84.80033,0.01355,-0.04499,-0.07483
65,NaN,NaN,NaN,9.58979,0.05779,-0.01343,-0.00697
66,NaN,NaN,NaN,-2.98810,0.04912,-0.02833,-0.03858
68,NaN,NaN,NaN,3.20407,-0.00190,0.09637,0.14240
70,NaN,NaN,NaN,-12.91579,0.21459,-0.02530,-0.02974
71,NaN,NaN,NaN,-5.55285,-0.02776,0.04008,0.06850
72,NaN,NaN,NaN,12.14721,0.03503,-0.01512,0.00769
73,NaN,NaN,NaN,-1.16657,-0.02462,-0.00753,-0.00115
74,NaN,NaN,NaN,-1.93146,-0.02140,0.04759,0.10548
76,NaN,NaN,NaN,-17.05840,-0.01335,-0.02877,-0.03394
77,NaN,NaN,NaN,2.27283,0.02918,0.03557,0.03198
78,NaN,NaN,NaN,2.12993,0.00584,0.02196,0.07252
80,NaN,NaN,NaN,-11.73544,0.09150,0.00881,-0.01925
82,NaN,NaN,NaN,1.70290,0.04439,-0.02543,-0.02125
83,NaN,NaN,NaN,-9.81515,-0.01262,-0.04019,-0.05646
85,NaN,NaN,NaN,8.57282,-0.02714,0.03784,0.08415
87,NaN,NaN,NaN,-9.98851,0.00348,-0.02184,-0.08564
93,NaN,NaN,NaN,1.24817,-0.03704,-0.02750,0.00213
94,NaN,NaN,NaN,1.65434,0.04604,0.00346,0.02641
95,NaN,NaN,NaN,0.02955,-0.01713,0.00224,-0.00774
98,NaN,NaN,NaN,11.78038,-0.01769,0.03439,0.06853
99,NaN,NaN,NaN,-7.18146,0.08436,0.08106,0.12286
100,NaN,NaN,NaN,-5.47030,-0.04432,0.01097,0.02510
103,NaN,NaN,NaN,9.29006,0.01273,-0.00405,-0.04024
104,NaN,NaN,NaN,-14.47812,-0.10064,-0.00063,-0.03520
106,NaN,NaN,NaN,0.00723,-0.03221,0.00123,0.00654
107,NaN,NaN,NaN,-15.34494,-0.06125,0.00701,0.02324
108,NaN,NaN,NaN,-6.27410,0.03216,-0.02121,-0.03315
thrombolysis,NaN,NaN,NaN,NaN,NaN,0.08027,0.10451
discharge_util,NaN,NaN,NaN,NaN,NaN,NaN,NaN
discharge_mrsleq2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
const,0.65851,0.04014,0.89629,37.83822,-0.06389,0.18726,-0.15301

Rename stroke team columns for display:

In [5]:
# Pick out stroke team names:
stroke_team_names = df_effects.index[df_effects.index.str.isnumeric()].values
# Make a dictionary to relabel them as team_t:
dict_stroke_team_names = dict(zip(stroke_team_names, [f'team_{t}' for t in stroke_team_names]))
# Make a dictionary for the other index names to remain unchanged:
dict_index_names = dict(zip(df_effects.index, df_effects.index)) | dict_stroke_team_names

# Apply rename:
df_effects.index = df_effects.index.map(dict_index_names)

Check that rename worked:

In [6]:
df_effects.iloc[42:45]

,precise_onset_known,afib_anticoagulant,prior_util,arrival_to_scan_time,thrombolysis,discharge_util,discharge_mrsleq2
team_51,NaN,NaN,NaN,-14.92004,-0.02806,0.00063,0.06909
team_55,NaN,NaN,NaN,-2.85577,0.01118,0.08430,0.12274
team_56,NaN,NaN,NaN,-13.06753,-0.09347,0.01694,0.02346

## Function for making the formula

This uses the effects data to build up a formula as a text string.

In [7]:
def make_formula_string(df_effects, col, simplify_teams=False):   
    # Pick out values for this feature:
    s = df_effects[col].dropna()
    
    # Place formula in here:
    formula_bits = [f'{col} =']
    for i in s.index:
        s_here = f'{s.loc[i]:+.2f}'
        if i != 'const':
            # Add this name to the formula.
            s_here += f'×{i}'
        formula_bits.append(s_here)

    if simplify_teams:
        team_bits = []
        nonteam_bits = []
        for f in formula_bits:
            if 'team_' in f:
                team_bits.append(f)
            else:
                nonteam_bits.append(f)
        formula_str = ' '.join(nonteam_bits) + ' +lots of stroke teams'
    else:
        formula_str = ' '.join(formula_bits)
    # Place a space after each + and -:
    formula_str = formula_str.replace('+', '+ ')
    formula_str = formula_str.replace('-', '- ')
    return formula_str

Example for one feature:

In [8]:
# Make formula for this feature:
col = df_effects.columns[0]

formula_str = make_formula_string(df_effects, col)
print(formula_str)

precise_onset_known = - 0.66×onset_during_sleep + 0.66

Run for all features.

Features that don't use stroke team:

In [9]:
for col in df_effects.columns[:3]:
    print(make_formula_string(df_effects, col))

precise_onset_known = - 0.66×onset_during_sleep + 0.66
afib_anticoagulant = + 0.63×atrial_fibrillation + 0.04
prior_util = - 0.12×age_80plus + 0.90

Other features:

In [10]:
print(make_formula_string(df_effects, 'arrival_to_scan_time', simplify_teams=True))

arrival_to_scan_time = + 37.84 + lots of stroke teams

In [11]:
print(make_formula_string(df_effects, 'thrombolysis', simplify_teams=True))

thrombolysis = - 0.12×onset_during_sleep + 0.14×precise_onset_known + 0.36×prior_util - 0.04×age_80plus - 0.06×stroke_severity_mild + 0.19×stroke_severity_moderate - 0.05×stroke_severity_severe - 0.00×arrival_to_scan_time - 0.06 + lots of stroke teams

In [12]:
print(make_formula_string(df_effects, 'discharge_mrsleq2', simplify_teams=True))

discharge_mrsleq2 = - 0.02×atrial_fibrillation + 0.78×prior_util - 0.15×age_80plus + 0.19×stroke_severity_mild - 0.14×stroke_severity_moderate - 0.30×stroke_severity_severe + 0.10×thrombolysis - 0.15 + lots of stroke teams

In [13]:
# for x in range(6):
#     print(make_formula_string(df_effects, f'discharge_mrsleq{x}', simplify_teams=True))
#     print('')