In [31]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import random as rn
import seaborn as sns

In [32]:
num_samples=1000

### Stroke onset during sleep and Precise stroke onset known
* df_a- initial dataframe with data from one drive
* b= Stroke not happening during sleep + Precise onset not known
* c= Stroke happening during sleep + Precise onset not known
* d= Stroke not happening during sleep + Precise onset known
* e= Stroke happening during sleep + Precise onset known
* f1= Random choice of probability of stroke happening during sleep
* f2= Random choice of whether or not a patient has the precise onset known based on previous probabilities
* df_b= series of f1
* df_c= series of f2
* df_d= final dataframe with f1 and f2 combined

In [33]:
df_a=pd.read_csv("combo_sleep_precise.csv", index_col="precise_onset_known")

In [34]:
b=df_a.loc[0,"0"]#0.33568
c=df_a.loc[0,"1"]
d=df_a.loc[1,"0"]
e=df_a.loc[1,"1"]
#no quote marks for rows

b1=b/(b+d)
d1=d/(b+d)

c1=c/(c+e)
e1=e/(c+e)

In [35]:
num_rows = 1000
p = c+e
np.random.seed(42)
f1 = np.random.binomial(1, p, num_rows)


f2=np.full(num_rows,42)
inds_f1_0 = np.where(f1 == 0)
num_f1_0 = len(inds_f1_0[0])

inds_f1_1= np.where(f1==1)
num_f1_1= len(inds_f1_1[0])

f2_vals = np.random.choice([0, 1], num_f1_0, p=[b1,d1])
f2[inds_f1_0] = f2_vals

f1_vals=np.random.choice([0, 1], num_f1_1, p=[c1,e1])
f2[inds_f1_1]=f1_vals

In [36]:
df_b=pd.Series(f1)
df_c=pd.Series(f2)

In [37]:
df_d=pd.concat([df_b,df_c], axis=1)
df_d.columns=["Onset_during_sleep","Precise_onset_known"]
df_d

     Onset_during_sleep  Precise_onset_known
0                     0                    0
1                     0                    1
2                     0                    1
3                     0                    1
4                     0                    1
..                  ...                  ...
995                   0                    1
996                   0                    1
997                   0                    1
998                   0                    0
999                   0                    1

[1000 rows x 2 columns]

### AFib and Anticoagulation
* df_e- initial dataframe with data from one drive
* f= Patient without AF + Not on anticoagulant
* g= Patient with AF + Not on anticoagulant
* h= Patient without AF + On anticoagulant
* i= Patient with AF + On anticoagulant
* f1= Random choice of probability of patient having AF
* f2= Random choice of whether or not a patient is on anticoagulant based on previous probabilities
* df_f= series of f1
* df_g= series of f2
* df_h= final dataframe with f1 and f2 combined

In [38]:
df_e=pd.read_csv("combo_anticoag_afib.csv", index_col="afib_anticoagulant")

In [39]:
f=df_a.loc[0,"0"]
g=df_a.loc[0,"1"]
h=df_a.loc[1,"0"]
i=df_a.loc[1,"1"]

f1=f/(f+h)
h1=h/(f+h)

g1=g/(g+i)
i1=i/(g+i)

In [40]:
num_rows = 1000
p = g+i
np.random.seed(89)
f3 = np.random.binomial(1, p, num_rows)


f4=np.full(num_rows,42)
inds_f3_0 = np.where(f3 == 0)

num_f3_0 = len(inds_f3_0[0])

inds_f3_1= np.where(f3==1)
num_f3_1= len(inds_f3_1[0])

f4_vals = np.random.choice([0, 1], num_f3_0, p=[f1,h1])
f4[inds_f3_0] = f4_vals

f3_vals=np.random.choice([0, 1], num_f3_1, p=[g1,i1])
f4[inds_f3_1]=f3_vals

In [41]:
df_f=pd.Series(f3)
df_g=pd.Series(f4)

In [42]:
df_h=pd.concat([df_f,df_g], axis=1)
df_h.columns=["AF_patients","AF_patients_on_anticoagulants"]
df_h

     AF_patients  AF_patients_on_anticoagulants
0              0                              1
1              0                              1
2              0                              1
3              0                              0
4              0                              1
..           ...                            ...
995            0                              0
996            0                              1
997            0                              1
998            0                              1
999            0                              0

[1000 rows x 2 columns]

### Age and Prior disability
* df_i- initial dataframe with data from one drive
* f5= Random choice of probability of patient having disability between 0 to 5
* f2= Random choice of patient age based on previous probabilities
* df_j= final dataframe with f1 and f2 combined

In [43]:
df_i=pd.read_csv("combo_age_disability.csv", index_col="prior_disability")

In [44]:
vals_f5 = df_i.columns
probs_f5 = df_i.sum(axis='rows')
f5 = np.random.choice(vals_f5, size=num_samples, p=probs_f5)

In [45]:
f6 = np.full(len(f5), 42)
vals_f6 = df_i.index

for j in vals_f5:
    inds_j = np.where(f5 == j)
    num_j = len(inds_j[0])
    probs_j = df_i[j]
    probs_j = probs_j/ probs_j.sum()
    f6_j = np.random.choice(vals_f6, size=num_j, p=probs_j)
    f6[inds_j] = f6_j
    print(j, num_j, probs_j, f6_j)

37.5 24 prior_disability
0    0.850438
1    0.083032
2    0.030428
3    0.024755
4    0.009799
5    0.001547
Name: 37.5, dtype: float64 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
42.5 17 prior_disability
0    0.848158
1    0.087675
2    0.027954
3    0.021601
4    0.013342
5    0.001271
Name: 42.5, dtype: float64 [1 0 0 1 0 0 0 0 0 0 1 0 1 0 0 0 1]
47.5 23 prior_disability
0    0.817359
1    0.104484
2    0.041958
3    0.024270
4    0.009050
5    0.002879
Name: 47.5, dtype: float64 [0 0 0 0 0 0 0 0 1 0 1 2 0 0 3 0 0 3 0 0 0 3 0]
52.5 51 prior_disability
0    0.790403
1    0.116734
2    0.045118
3    0.032705
4    0.011936
5    0.003103
Name: 52.5, dtype: float64 [0 0 1 2 0 0 0 0 0 0 0 0 3 0 3 0 0 0 0 0 0 0 5 1 0 0 4 0 0 0 0 3 1 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
57.5 59 prior_disability
0    0.750952
1    0.133300
2    0.056963
3    0.037258
4    0.017884
5    0.003643
Name: 57.5, dtype: float64 [0 0 1 1 0 1 0 2 0 2 1 0 0 1 3 1 0 0 0 0 0 0 3 0 0 1 0 0 2 1 1 0 0 0 1 0 0
 0 1 0 0 1 0 0 0 1 0 0 1 1 0 0 0 0 0 1 0 0 0]
62.5 73 prior_disability
0    0.705610
1    0.158043
2    0.065092
3    0.046989
4    0.019643
5    0.004622
Name: 62.5, dtype: float64 [0 0 0 0 0 1 1 0 2 1 0 0 0 3 0 0 0 0 0 0 0 1 0 2 0 0 0 0 0 0 0 0 1 0 0 2 0
 0 0 0 0 0 0 0 0 1 1 0 0 2 0 0 0 2 1 1 0 0 1 0 0 1 0 2 3 2 0 0 0 1 1 3 0]
67.5 84 prior_disability
0    0.646923
1    0.181988
2    0.079599
3    0.059342
4    0.026203
5    0.005945
Name: 67.5, dtype: float64 [0 0 1 0 1 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 2 2 2 0 0 0 3 0 5 0 0 0 1
 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 1 0 1 3 0 0 0 1 0 0 0 0 3 0 0 0 0 0 0 0
 0 1 0 1 0 2 0 1 1 3]
72.5 113 prior_disability
0    0.588105
1    0.204594
2    0.088679
3    0.075964
4    0.033798
5    0.008860
Name: 72.5, dtype: float64 [0 0 0 0 0 0 1 2 0 0 0 3 1 0 1 1 0 0 0 0 4 0 0 0 4 0 1 0 1 0 1 0 0 0 1 0 1
 0 3 3 0 4 3 5 1 0 0 0 0 1 0 1 0 0 0 0 0 0 1 0 1 2 0 0 0 0 0 1 0 5 0 3 0 0
 0 0 1 2 0 4 0 0 0 3 0 1 0 1 1 0 0 0 1 2 1 0 0 0 0 1 1 0 0 1 2 1 0 0 0 0 0
 2 0]
77.5 155 prior_disability
0    0.512663
1    0.222883
2    0.106997
3    0.099770
4    0.046112
5    0.011576
Name: 77.5, dtype: float64 [1 0 1 0 2 1 3 0 0 3 0 1 0 1 0 0 0 2 2 1 0 0 0 0 0 0 1 4 0 0 1 0 0 0 0 0 0
 1 1 0 0 1 0 0 2 0 0 3 2 2 0 2 0 0 0 1 0 2 0 0 1 3 0 0 0 0 0 0 2 0 1 0 0 0
 1 3 0 0 3 0 0 0 2 2 0 0 0 0 1 0 1 1 0 1 1 1 1 0 1 0 1 0 0 3 1 0 0 3 0 0 1
 2 0 0 1 0 1 3 1 0 0 0 1 3 3 0 0 0 0 3 0 0 2 0 0 0 0 0 0 0 0 0 3 0 0 0 3 1
 1 1 1 2 0 2 3]
82.5 169 prior_disability
0    0.395572
1    0.228336
2    0.141619
3    0.152119
4    0.066730
5    0.015623
Name: 82.5, dtype: float64 [2 0 0 1 1 0 0 1 0 2 1 2 3 0 0 1 1 2 0 2 3 0 0 0 1 1 0 0 2 2 0 0 1 0 1 0 0
 3 0 0 2 3 4 0 0 0 2 0 4 4 4 0 0 1 2 0 0 2 1 3 1 0 4 3 0 0 1 0 0 0 0 0 0 0
 2 0 1 0 0 3 4 4 0 3 3 1 1 2 0 1 4 3 0 0 5 0 3 0 3 1 4 0 0 2 3 0 2 0 1 1 0
 4 0 1 0 3 2 0 1 1 0 0 4 2 0 0 0 0 4 5 0 0 1 1 1 0 2 4 0 0 4 1 0 0 1 0 0 2
 1 1 3 0 0 0 0 0 3 0 1 3 1 1 4 3 0 3 2 1 4]
87.5 120 prior_disability
0    0.284265
1    0.206364
2    0.160285
3    0.215771
4    0.109943
5    0.023370
Name: 87.5, dtype: float64 [2 2 2 1 2 2 0 0 0 2 1 2 5 1 3 2 4 0 2 0 0 2 2 1 1 1 0 0 5 1 1 3 3 3 1 3 0
 1 5 1 0 1 3 0 1 4 0 3 3 4 2 0 1 4 0 3 5 0 1 1 2 0 2 3 4 0 3 1 3 5 1 2 3 2
 0 3 3 3 3 1 1 0 3 4 0 5 1 5 2 3 0 0 0 0 1 2 0 4 1 2 4 3 4 2 1 0 4 1 5 3 0
 0 1 2 2 3 3 0 4 3]
92.5 112 prior_disability
0    0.153814
1    0.149387
2    0.159168
3    0.303923
4    0.190981
5    0.042726
Name: 92.5, dtype: float64 [2 2 1 3 4 2 3 2 1 0 0 5 4 3 3 2 0 3 5 3 0 2 4 3 3 4 2 3 0 0 0 3 3 4 3 1 3
 0 3 3 3 0 3 1 4 2 1 1 1 3 4 3 4 1 3 2 3 4 1 4 1 3 4 3 0 1 4 4 4 5 4 5 4 0
 2 0 3 3 3 1 3 3 1 1 4 0 0 0 4 2 4 3 5 0 0 3 0 4 1 3 0 3 3 0 3 3 1 1 5 2 3
 3]

In [49]:
df_j=pd.DataFrame([f5, f6]).T
df_j.columns=["Patient age","Disabilities (0-5)"]
df_j

    Patient age Disabilities (0-5)
0          52.5                  0
1          77.5                  1
2          62.5                  0
3          72.5                  0
4          62.5                  0
..          ...                ...
995        72.5                  0
996        57.5                  0
997        77.5                  3
998        37.5                  0
999        52.5                  0

[1000 rows x 2 columns]

### Arrival to scan time and stroke teams

In [50]:
df_k=pd.read_csv("arrival_to_scan_time_stats_by_stroke_team.csv", index_col="stats")

In [72]:
df_l=pd.read_csv("stroke_team.csv")
n=df_l["stroke_team"]
np.random.seed(42)
stroke_team_number=np.random.choice(n,num_samples,p=df_l["count"])

In [73]:
stn=pd.Series(stroke_team_number)

In [74]:
team_names=df_k.columns
f9=np.full(num_samples,42)

for o in team_names:
    p=df_k.loc["mu_for_lognorm", o]
    q=df_k.loc["sigma_for_lognorm", o]

    if int(o) in stn.value_counts().index:
        r=stn.value_counts()[int(o)]
    else:
        r=0

    f8 = np.random.default_rng()
    n_gen = f8.lognormal(p, q, size=r)

    inds_f8_0 = np.where(stroke_team_number == int(o))
    f9[inds_f8_0] = n_gen

In [76]:
df_m=pd.DataFrame([pp, f9]).T
df_m.columns=["Stroke team","Arrival to scan time"]
df_m

     Stroke team  Arrival to scan time
0             64                    56
1             42                    35
2             12                    22
3              5                   129
4             79                   579
..           ...                   ...
995           87                     3
996           73                     5
997           10                   156
998           42                    35
999           75                    17

[1000 rows x 2 columns]

### Stroke severity

In [98]:
df_n=pd.read_csv("stroke_severity.csv")
s_s=df_n["stroke_severity"]
np.random.seed(42)
s=np.random.choice(s_s,num_samples,p=df_n["count"])

In [99]:
df_o=pd.DataFrame(s)
df_o.columns=["Stroke severity"]

Final Big Dataframe

In [100]:
results=pd.concat([df_d, df_h, df_j, df_m, df_o], axis=1)

In [101]:
results

,Onset_during_sleep,Precise_onset_known,AF_patients,AF_patients_on_anticoagulants,Patient age,Disabilities (0-5),Stroke team,Arrival to scan time,Stroke severity
0,0,0,0,1,52.5,0,64,56,5.0
1,0,1,0,1,77.5,1,42,35,25.0
2,0,1,0,1,62.5,0,12,22,13.0
3,0,1,0,0,72.5,0,5,129,9.0
4,0,1,0,1,62.5,0,79,579,3.0
...,...,...,...,...,...,...,...,...,...
995,0,1,0,0,72.5,0,87,3,2.0
996,0,1,0,1,57.5,0,73,5,23.0
997,0,1,0,1,77.5,3,10,156,3.0
998,0,0,0,1,37.5,0,42,35,25.0
999,0,1,0,0,52.5,0,75,17,6.0

In [103]:
results.to_csv("generated_dependant_data.csv", index=False)