# Test notebook

Testing

In [5]:
import pandas as pd

Exception ignored in PyObject_HasAttr(); consider using PyObject_HasAttrWithError(), PyObject_GetOptionalAttr() or PyObject_GetAttr():
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
AttributeError: partially initialized module 'pandas' from 'c:\Users\gk442\AppData\Local\miniconda3\Lib\site-packages\pandas\__init__.py' has no attribute '_pandas_parser_CAPI' (most likely due to a circular import)

In [6]:
name=input("What is your name?")
age=int(input("How old are you?"))

print(f"Hello {name}! You will be {age+10} years old in 10 years time.")

Hello Gurnoor! You will be 31 years old in 10 years time.

In [7]:
a=int(input("How much is your monthly take home income?"))
b=int(input("How much is your monthly housing cost?"))
c=int(input("How much do you spend on food monthly"))
d=int(input("How much do you spend on utilities monthly?"))

e= a-(b+c+d)

print(f"Hello {name}! You make {a} in a month and after excluding housing, food and utilities, your total savings are {e}")

Hello Gurnoor! You make 9293 in a month and after excluding housing, food and utilities, your total savings are 5686

Extending and joining dataframes

In [8]:
df_a=pd.DataFrame(
    [{"Name":"Dan","Trainer?":"Yes"},
     {"Name":"Sammi","Trainer?":"Yes"}]
)

df_b=pd.DataFrame(
    [{"Name":"Mike","Trainer?":"No"},
     {"Name":"Tom","Trainer?":"No"}]
)

In [9]:
df_a

    Name Trainer?
0    Dan      Yes
1  Sammi      Yes

In [10]:
df_b

   Name Trainer?
0  Mike       No
1   Tom       No

In [11]:
df_c=pd.concat([df_a,df_b],axis=0)
df_c

    Name Trainer?
0    Dan      Yes
1  Sammi      Yes
0   Mike       No
1    Tom       No

In [13]:
#this set has duplicate index values so to reset this we use reset function
df_c.reset_index()

   index   Name Trainer?
0      0    Dan      Yes
1      1  Sammi      Yes
2      0   Mike       No
3      1    Tom       No

In [14]:
#this has now become a new column so to avoid this let's use drop=True
df_c.reset_index(drop=True)

    Name Trainer?
0    Dan      Yes
1  Sammi      Yes
2   Mike       No
3    Tom       No

In [ ]:
row_to_add=[4,"Allen","Yes"]
df_c=row_to_add

df_c
#ASK QUESTION: why is it not joining the rest of the table

[4, 'Allen', 'Yes']